# Generated by Django 5.1.6 on 2025-12-01 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('secondary_education_p', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Pourcentage d'éducation secondaire")),
                ('education_board_type', models.CharField(choices=[('Central', 'Central'), ('Others', 'Autres')], max_length=10)),
                ('higher_secondary_p', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Pourcentage d'éducation supérieure secondaire")),
                ('h_education_board_type', models.CharField(choices=[('Central', 'Central'), ('Others', 'Autres')], max_length=10)),
                ('higher_secondary_specialization', models.CharField(choices=[('Commerce', 'Commerce'), ('Science', 'Science'), ('Arts', 'Arts')], max_length=20)),
                ('degree_p', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de diplôme')),
                ('degree_type', models.CharField(choices=[('Sci&Tech', 'Sciences & Technologie'), ('Comm&Mgmt', 'Commerce & Management'), ('Others', 'Autres')], max_length=20)),
                ('work_experience', models.CharField(choices=[('Yes', 'Oui'), ('No', 'Non')], max_length=3)),
                ('etest_p', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Pourcentage de test d'entrée")),
                ('specialisation', models.CharField(choices=[('Mkt&HR', 'Marketing & RH'), ('Mkt&Fin', 'Marketing & Finance')], max_length=10)),
                ('mba_p', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage MBA')),
                ('probabilite_placement', models.FloatField(blank=True, null=True, verbose_name='Probabilité de placement (%)')),
                ('prediction', models.BooleanField(blank=True, null=True, verbose_name='Prédiction (Placé/Non placé)')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
