# Generated by Django 5.1.6 on 2025-12-01 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='probabilite_placement',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='degree_p',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Degree %'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='degree_type',
            field=models.CharField(choices=[('Sci&Tech', 'Sciences & Technologie'), ('Comm&Mgmt', 'Commerce & Management'), ('Others', 'Autres')], max_length=20, verbose_name='Degree Type'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='education_board_type',
            field=models.CharField(choices=[('Central', 'Central'), ('Others', 'Autres')], max_length=10, verbose_name='Education Board Type'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='etest_p',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Etest %'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='h_education_board_type',
            field=models.CharField(choices=[('Central', 'Central'), ('Others', 'Autres')], max_length=10, verbose_name='H Education Board Type'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='higher_secondary_p',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Higher Secondary %'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='higher_secondary_specialization',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Science', 'Science'), ('Arts', 'Arts')], max_length=20, verbose_name='Higher Secondary Specialization'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='mba_p',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MBA %'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='secondary_education_p',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Secondary Education %'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='specialisation',
            field=models.CharField(choices=[('Mkt&HR', 'Marketing & RH'), ('Mkt&Fin', 'Marketing & Finance')], max_length=10, verbose_name='Specialisation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='work_experience',
            field=models.CharField(choices=[('Yes', 'Oui'), ('No', 'Non')], max_length=3, verbose_name='Work Experience'),
        ),
    ]
