# Generated by Django 5.1.6 on 2025-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_candidat_options_remove_candidat_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['-probabilite_performance', '-date_creation'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='prediction_performance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Prédiction (Performant/Non performant)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='probabilite_performance',
            field=models.FloatField(blank=True, null=True, verbose_name='Probabilité de performance (%)'),
        ),
    ]
